name: CI setup node
description: pnpm, Node, Turbo cache, and install with frozen lockfile. Run actions/checkout before this action.

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      # version comes from root package.json "packageManager" (single source of truth)

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24.13.1"
        cache: "pnpm"
        cache-dependency-path: |
          **/pnpm-lock.yaml

    # Align with Node cache (cache-dependency-path: **/pnpm-lock.yaml) to avoid stale cache.
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
