packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  # Framework & Runtime
  next: ^15.1.6
  react: ^19.0.0
  react-dom: ^19.0.0
  
  # Testing
  vitest: ^3.0.3
  '@testing-library/react': ^16.1.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.5.2
  jsdom: ^25.0.1
  '@vitejs/plugin-react': ^4.3.4
  
  # TypeScript
  typescript: ^5.7.2
  '@types/node': ^22.10.5
  '@types/react': ^19.0.6
  '@types/react-dom': ^19.0.2
  
  # Storybook
  storybook: ^8.5.3
  '@storybook/react': ^8.5.3
  '@storybook/react-vite': ^8.5.3
  '@storybook/addon-essentials': ^8.5.3
  '@storybook/addon-interactions': ^8.5.3
  '@storybook/addon-a11y': ^8.5.3
  '@storybook/test': ^8.5.3
  '@storybook/blocks': ^8.5.3
  
  # Styling
  tailwindcss: ^4.0.0
  '@tailwindcss/postcss': ^4.1.14
  '@tailwindcss/vite': ^4.1.14
  postcss: ^8.5.6
  clsx: ^2.1.1
  
  # Build Tools
  vite: ^6.0.7
  
  # Documentation
  vitepress: 1.6.4
  'search-insights': ^1.10.0
  vue: ^3.5.13
  '@vue/server-renderer': ^3.5.13