# pnpm workspace root
packages:
  - 'apps/*'
  - 'docs'
  - 'packages/*'
  - 'tools/*'

catalog:
  # Framework & Runtime
  next: ^15.1.6
  react: ^19.2.4
  react-dom: ^19.2.4

  # Testing
  vitest: ^4.0.0
  '@testing-library/react': ^16.3.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.5.2
  happy-dom: ^20.7.0
  '@vitejs/plugin-react': ^5.0.0
  '@playwright/test': ^1.58.2

  # TypeScript
  typescript: ^5.7.2
  '@types/node': ^22.10.5
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  
  # Storybook
  storybook: ^8.5.3
  '@storybook/react': ^8.5.3
  '@storybook/react-vite': ^8.5.3
  '@storybook/addon-essentials': ^8.5.3
  '@storybook/addon-interactions': ^8.5.3
  '@storybook/addon-a11y': ^8.5.3
  '@storybook/test': ^8.5.3
  '@storybook/blocks': ^8.5.3
  
  # Styling
  tailwindcss: ^4.2.1
  '@tailwindcss/postcss': ^4.2.1
  '@tailwindcss/vite': ^4.2.1
  '@tailwindcss/cli': ^4.2.1
  postcss: ^8.5.6
  clsx: ^2.1.1
  
  # Build Tools
  vite: ^7.3.1

  # Documentation
  vitepress: 1.6.4
  vue: ^3.5.28
  '@vue/server-renderer': ^3.5.28