name: CI setup
description: Checkout, pnpm, Node, Turbo cache, and install with frozen lockfile.

inputs:
  fetch-depth:
    description: Git fetch depth for checkout (0 = full history).
    required: false
    default: "0"
  include-checkout:
    description: When true, run checkout in this action. Set to true when no checkout step runs before ci-setup; false when the workflow already checked out.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: inputs.include-checkout == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      with:
        version: 9.12.2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"
        cache-dependency-path: |
          **/pnpm-lock.yaml

    # Align with Node cache (cache-dependency-path: **/pnpm-lock.yaml) to avoid stale cache.
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
