import type { HomeLesson } from '@game-client/ui/screens/home/view/home-view';

export const posterLesson = {
  id: 'lesson-full-alphabet',
  title: 'All the letters',
  items: [
    { id: 'letter-ani', targetScript: 'ა', transliteration: 'a', type: 'letter' },
    { id: 'letter-bani', targetScript: 'ბ', transliteration: 'b', type: 'letter' },
    { id: 'letter-gani', targetScript: 'გ', transliteration: 'g', type: 'letter' },
    { id: 'letter-doni', targetScript: 'დ', transliteration: 'd', type: 'letter' },
    { id: 'letter-eni', targetScript: 'ე', transliteration: 'e', type: 'letter' },
    { id: 'letter-vini', targetScript: 'ვ', transliteration: 'v', type: 'letter' },
    { id: 'letter-zeni', targetScript: 'ზ', transliteration: 'z', type: 'letter' },
    { id: 'letter-tani', targetScript: 'თ', transliteration: 't', type: 'letter' },
    { id: 'letter-ini', targetScript: 'ი', transliteration: 'i', type: 'letter' },
    { id: 'letter-kani', targetScript: 'კ', transliteration: "k'", type: 'letter' },
    { id: 'letter-lasi', targetScript: 'ლ', transliteration: 'l', type: 'letter' },
    { id: 'letter-mani', targetScript: 'მ', transliteration: 'm', type: 'letter' },
    { id: 'letter-nari', targetScript: 'ნ', transliteration: 'n', type: 'letter' },
    { id: 'letter-oni', targetScript: 'ო', transliteration: 'o', type: 'letter' },
    { id: 'letter-pari', targetScript: 'პ', transliteration: "p'", type: 'letter' },
    { id: 'letter-zhani', targetScript: 'ჟ', transliteration: 'zh', type: 'letter' },
    { id: 'letter-rae', targetScript: 'რ', transliteration: 'r', type: 'letter' },
    { id: 'letter-sani', targetScript: 'ს', transliteration: 's', type: 'letter' },
    { id: 'letter-tari', targetScript: 'ტ', transliteration: "t'", type: 'letter' },
    { id: 'letter-uni', targetScript: 'უ', transliteration: 'u', type: 'letter' },
    { id: 'letter-pari-aspirated', targetScript: 'ფ', transliteration: 'p', type: 'letter' },
    { id: 'letter-kani-aspirated', targetScript: 'ქ', transliteration: 'k', type: 'letter' },
    { id: 'letter-ghani', targetScript: 'ღ', transliteration: 'gh', type: 'letter' },
    { id: 'letter-qari', targetScript: 'ყ', transliteration: "q'", type: 'letter' },
    { id: 'letter-shini', targetScript: 'შ', transliteration: 'sh', type: 'letter' },
    { id: 'letter-chini', targetScript: 'ჩ', transliteration: 'ch', type: 'letter' },
    { id: 'letter-tsani', targetScript: 'ც', transliteration: 'ts', type: 'letter' },
    { id: 'letter-dzili', targetScript: 'ძ', transliteration: 'dz', type: 'letter' },
    { id: 'letter-tsili', targetScript: 'წ', transliteration: "ts'", type: 'letter' },
    { id: 'letter-chari', targetScript: 'ჭ', transliteration: "ch'", type: 'letter' },
    { id: 'letter-khani', targetScript: 'ხ', transliteration: 'kh', type: 'letter' },
    { id: 'letter-jani', targetScript: 'ჯ', transliteration: 'j', type: 'letter' },
    { id: 'letter-hae', targetScript: 'ჰ', transliteration: 'h', type: 'letter' },
  ],
} satisfies HomeLesson;
