name: App Cleanup Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

concurrency:
  group: app-cleanup-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove Vercel Preview Deployment
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--yes'
          scope: ${{ secrets.VERCEL_ORG_ID }}
