name: App Deploy (Main)

on:
  push:
    branches: [main]
    paths:
      - 'apps/game-client/**'
      - 'packages/ui/**'
      - 'packages/theme/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: app-deploy-main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            **/pnpm-lock.yaml
      
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build game client and dependencies
        run: pnpm turbo run build
      
      - name: Debug file structure
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Root directory contents ==="
          ls -la
          echo "=== apps directory contents ==="
          ls -la apps/
          echo "=== game-client directory contents ==="
          ls -la apps/game-client/
          echo "=== game-client build output ==="
          ls -la apps/game-client/.next/ 2>/dev/null || echo "No .next directory found"
          echo "=== game-client package.json ==="
          cat apps/game-client/package.json
          echo "=== Working directory for Vercel ==="
          ls -la apps/game-client/
      
      - name: Create deployment artifact
        run: |
          # Create a tar archive of the game-client directory for debugging
          tar -czf game-client-debug.tar.gz apps/game-client/
          echo "Created debug artifact: game-client-debug.tar.gz"
          ls -la game-client-debug.tar.gz
      
      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-client-debug
          path: game-client-debug.tar.gz
          retention-days: 1
      
      - name: Pre-deployment verification
        run: |
          echo "=== Pre-deployment verification ==="
          echo "Current directory: $(pwd)"
          echo "Contents of apps/game-client:"
          ls -la apps/game-client/
          echo "Checking if .next directory exists:"
          if [ -d "apps/game-client/.next" ]; then
            echo "✅ .next directory exists"
            ls -la apps/game-client/.next/
          else
            echo "❌ .next directory does not exist"
          fi
          echo "Checking if package.json exists:"
          if [ -f "apps/game-client/package.json" ]; then
            echo "✅ package.json exists"
          else
            echo "❌ package.json does not exist"
          fi
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}
