name: App Deploy (PR)

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run typecheck
      - run: pnpm turbo run lint
      - run: pnpm turbo run test

