name: Docs Generate LLM Bundle
description: Generates LLM documentation bundle and uploads as artifact
# Triggers: push to main, PRs (docs changes), manual
# Purpose: Create kartuli-llm.txt with all documentation for LLM consumption
# Output: Artifact containing generated bundle (no git commits)

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'tools/web-docs-client/**'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'tools/web-docs-client/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-bundle:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        run: npm install -g pnpm@9.12.2
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Generate LLM bundle
        run: |
          cd tools/web-docs-client
          node scripts/generate-llm-bundle.js
      
      - name: Upload LLM bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kartuli-llm-bundle
          path: docs/kartuli-llm.txt
          retention-days: 30
